var levels = [
	{ map: [
		X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X, X, X, X,  
		X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X, X, X, X,
		X,	X,	G,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X, X, X, X,
		X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	E,	E,	E,	X,	X,	X,	X, X, X, X,
		X,	X,	G,	G,	X,	X,	X,	X,	X,	X,	X,	E,	E,	E,	X,	X,	X,	X, X, X, X,
		X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	E,	E,	E,	X,	X,	X,	X, X, X, X,
		X,	X,	X,	X,	X,	D,	0,	G,	G,	0,	0,  0,	0,	0,	S,	X,	X,	X, X, X, X  ],
	  background: "background.png",
	  monsterCount: 1,
	  numcols:  21},
	{ map: [
		X,	X,	X,	X,	0,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X, X, X, X,  
		X,	X,	X,	X,	0,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X, X, X, S,
		X,	X,	G,	X,	0,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X, X, X, 0,
		X,	X,	X,	X,	0,	X,	0,	0,	D,	X,	X,	E,	E,	E,	X,	X,	X,	X, X, X, 0,
		X,	X,	G,	G,	X,	X,	X,	X,	0,	X,	X,	E,	E,	E,	X,	X,	X,	X, X, X, 0,
		X,	X,	X,	X,	X,	X,	X,	X,	0,	X,	X,	E,	E,	E,	0,	0,	0,	0, 0, 0, 0,
		X,	X,	X,	X,	X,	X,	X,	X,	0,	0,	0,	0,	0,	0,	0,	X,	X,	X, X, X, X  ],
	  background: "background.png",
	  monsterCount: 1,
	  numcols:  21},
	{ map: [
		X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X, X, X, X,  
		X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X,	X, X, X, X,
		X,	D,	E,	E,	E,	E,	E,	E,	E,	E,	E,	E,	E,	E,	E,	E,	E,	E, E, S, 0,
		X,	0,	X,	X,	X,	X,	X,	0,	0,	0,	X,	X,	X,	X,	X,	X,	X,	X, X, X, 0,
		X,	0,	X,	X,	X,	X,	X,	X,	0,	X,	X,	X,	X,	X,	X,	X,	X,	X, X, X, 0,
		X,	0,	X,	X,	X,	X,	X,	X,	0,	X,	X,	X,	X,	X,	X,	X,	X,	X, X, X, 0,
		X,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0, 0, 0, 0  ],
	  background: "background.png",
	  monsterCount: 0,
	  numcols:  21},
];